### ISSUE TITLE
Long running processes appear to fail quietly

### ISSUE THREAD

**Issue by sbsends** [signalwire/signalwire-golang#89]
I have a long running, but fairly basic relay instance that stops receiving/responding to messages after a while. The server works as expected following a reboot but will eventually fail if enough time passes. I am logging all errors but unfortunately nothing is showing up. I believe this is due to the call back functions not getting called after a connection failure. 

```golang
// NewConsumer creates a signalwire consumer
func NewConsumer(project string, token string, context string) *signalwire.Consumer {
	consumer := new(signalwire.Consumer)
	// setup the Client
	consumer.Setup(project, token, []string{context})
	// register callback
	consumer.Ready = func(consumer *signalwire.Consumer) {
		fmt.Println("CONSUMER IS READY ✅")
	}

	consumer.OnIncomingMessage = func(consumer *signalwire.Consumer, msgObj *signalwire.MsgObj) {
		if strings.ToLower(msgObj.GetBody()) == "unstop" {
			return
		}
		LogMessage(msgObj)
		numberDoc, err := data.GetDoc(msgObj.GetTo())
		if err != nil {
			LogError(err)
			return
		}
		if Contains(numberDoc.Owners, msgObj.GetFrom()) {

			var followUp string
			if len(numberDoc.Subscribers) > 0 {
				LogMessageResult(consumer.Client.Messaging.Send(msgObj.GetTo(), msgObj.GetFrom(), context, Sending))
				mg := NewMessageGroup(consumer.Client, msgObj.GetTo(), context)
				mg.SetMessageDetails(numberDoc.Subscribers, msgObj.GetBody())
				result := mg.SendMassMessage()
				followUp = fmt.Sprintf(SuccessfulDelivery, (len(result.AllRecipients) - len(result.Undelivered)))
				LogMessageResult(consumer.Client.Messaging.Send(msgObj.GetTo(), msgObj.GetFrom(), context, followUp))
				data.RemoveSubscriber(msgObj.GetTo(), result.OptedOut)
			} else {
				followUp := fmt.Sprintf(NoSubscribers, SetupHelpURL)
				LogMessageResult(consumer.Client.Messaging.Send(msgObj.GetTo(), msgObj.GetFrom(), context, followUp))
			}
		} else if Contains(numberDoc.Subscribers, msgObj.GetFrom()) {
			// msg from a subscriber
			followUp := fmt.Sprintf(SubscriberTexting, FeedbackURL)
			LogMessageResult(consumer.Client.Messaging.Send(msgObj.GetTo(), msgObj.GetFrom(), context, followUp))
		} else {
			// non-subscriber
			data.AddSubscriber(msgObj.GetTo(), msgObj.GetFrom())
			followUp := fmt.Sprintf(SuccessfullySubscribed, numberDoc.BusinessName)
			LogMessageResult(consumer.Client.Messaging.Send(msgObj.GetTo(), msgObj.GetFrom(), context, followUp))

			for _, owner := range numberDoc.Owners {
				LogMessageResult(consumer.Client.Messaging.Send(msgObj.GetTo(), owner, context, NewSubscriber))
			}
		}
	}
	consumer.Teardown = func(consumer *signalwire.Consumer) {
		fmt.Println("TEARING DOWN CONSUMER 💀")
	}
	return consumer
}
```

Is there anyway to add a handler that gets called when a connection fails, or even better, reestablish a connection?

**Comment by dragos-oancea** [comment]
thanks for reporting. you could try this PR until we merge it: 
https://github.com/signalwire/signalwire-golang/pull/90

**Comment by dragos-oancea** [comment]
try current master branch. we merged #90

**Comment by sbsends** [comment]
Sweet 👍
Just to clarify I don't need to change anything on the consumer it will handle reconnects automatically?

**Comment by sbsends** [comment]
I hate to bring bad news but the service is still failing silently. I am using the latest version. No changes to the consumer (posted above)

```
#go mod
go 1.14
require (
	github.com/signalwire/signalwire-golang/signalwire v0.0.0-20200614205519-a9d4530b1282
)
```

**Comment by dragos-oancea** [comment]
are you sure you don't see this in the logs ? 
Log.Debug("missed 3 pings from server, will reconnect.\n")

**Comment by dragos-oancea** [comment]
> Sweet 
> Just to clarify I don't need to change anything on the consumer it will handle reconnects automatically?

yes.

**Comment by sbsends** [comment]
I wasn't able to see anything. The program is running on kubernetes so I should be catching everything from stdout / stderr. 

If you would like I can share the entire repo with you. We really need the relay client to stay connected or at least let us know to reinitiate a connection.

**Comment by dragos-oancea** [comment]
Do you do this in your program ?
signalwire.Log.SetLevel(signalwire.DebugLevelLog) 
Does your program show debug logs ? 

If you share it I can give it a try by simulating a dropped connection with iptables (same thing I did before merging the patch) .
